/* generated by bootloader.pl */
#define BOOTLOADER_FREQ_KHZ 40000
#define BOOTLOADER_SRAMSZ_KB 0
#define BOOTLOADER_SDRAMSZ_MB 64
#define BOOTLOADER_BAUD 38400
#define CONFIG_KERNEL_COMMAND_LINE "console=ttyS0,38400"

#define BOOTLOADER_memcfg1  0x2c022
#define BOOTLOADER_memcfg2  0x86406020
#define BOOTLOADER_uart     0x83
#define BOOTLOADER_loopback 0x0
#define BOOTLOADER_flow     0x0
#define BOOTLOADER_ftreg    0x13b000

#define BOOTLOADER_grlib_sdram 0x8640013b
#define BOOTLOADER_ddr2spa_cfg1 0x91a082bc
#define BOOTLOADER_ddr2spa_cfg3 0x2150000
#define BOOTLOADER_ddrspa_cfg1 0xa1a082bc

#define BOOTLOADER_freq      40500000

#define BOOTLOADER_ramsize   0x3fff000
#define BOOTLOADER_romsize   0x1000000
#define BOOTLOADER_stack     0x43ffefe0

#define BOOTLOADER_physbase  0x40000000
